version: '3.8'

services:
  server:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/serviceAccountKey.json
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules